version: '2.4'
services:
 dnsmain:
   container_name: "dnsmain"
   hostname: "dnsmain"
   image: "bashmeunix/book:latest"
   ports:
     - "127.0.0.1:5000:5000"
     - "127.0.0.1:9095:9090"
   environment:
     - ENV=PROD
   volumes:
     - "./app:/app"
     - "./entry-point.sh:/entry-point.sh"
   depends_on:
     - resolver
     - redis
 resolver:
   container_name: "resolver"
   hostname: "resolver"
   image: "bashmeunix/ptr:0.1"
   depends_on:
     - redis
 redis:
   container_name: "redis"
   hostname: "redis"
   image: "redis:latest"
   volumes:
     - type: volume
       source: redis_db
       target: /data
volumes:
  redis_db:
