version: '3'
services:
 dockerapp:
  image: "bashmeunix/book:latest"
  ports:
   - "5000:5000"
  environment:
   - ENV=DEV
  volumes:
   - "./app:/app"
  links:
   - resolver
   - redis
 resolver:
  image: "bashmeunix/ptr:0.1"
 redis:
  image: "redis:latest"
