version: '3'
services:
 dockerapp:
  container_name: "app"
  image: "bashmeunix/book:latest"
  ports:
   - "5000:5000"
  environment:
   - ENV=UNIT
  volumes:
   - "./app:/app"
   - "./entry-point.sh:/entry-point.sh"
  links:
   - resolver
   - redis
 resolver:
  container_name: "resolver"
  image: "bashmeunix/ptr:0.1"
 redis:
  container_name: "redis"
  image: "redis:latest"
