version: '2.4'
services:
 proxy:
  container_name: "proxy"
  hostname: "proxy"
  build: proxy/
  #  volumes:
          #   - "./proxy/nginx.conf:/etc/nginx/conf.d/default.conf"
  ports:
   - "127.0.0.1:8080:80"
  environment:
   - NGINX_HOST=proxy.isnogood.ru
   - NGINX_PROXY=http://dockerapp:9090
  depends_on:
   - dockerapp    
 dockerapp:
  container_name: "app"
  hostname: "app"
  image: "bashmeunix/book:latest"
  ports:
    - "127.0.0.1:5000:5000"
    - "127.0.0.1:9095:9090"
      #  build: .
      # ports:
      # - "127.0.0.1:5000:5000"
      # - "127.0.0.1:9090:9090"
  environment:
   - ENV=PROD
  volumes:
   - "./app:/app"
   - "./entry-point.sh:/entry-point.sh"
  depends_on:
   - resolver
   - redis
 resolver:
  container_name: "resolver"
  hostname: "resolver"
  image: "bashmeunix/ptr:0.1"
  depends_on:
    - redis
 redis:
  container_name: "redis"
  hostname: redis
  image: "redis:latest"
 logspout:
  image: bashmeunix/logspout:0.1
  container_name: "logspout"
  hostname: "logspout"
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
  ports:
   - "8000:80"
  depends_on:
    logstash:
     condition: service_healthy
  restart: always
  command: logstash://logstash:5000
 logstash:
  container_name: "logstash"
  hostname: "logstash"
  image: logstash:6.8.8
  volumes:
   - ./logstash.conf:/etc/logstash.conf
  environment:
   ES_JAVA_OPTS: "-Xms512m -Xmx512m"
   LOGSPOUT: ignore
  healthcheck:
   test: ["CMD", "curl", "http://localhost:9600/"]
   interval: 3s
   timeout: 3s
   retries: 10
   start_period: 60s
  depends_on:
    - elasticsearch
  command: logstash -f /etc/logstash.conf
 elasticsearch:
   image: elasticsearch:6.8.8
   container_name: "elasticsearch"
   hostname: "elasticsearch"
   environment:
    LOGSPOUT: ignore
 kibana:
  image: kibana:6.8.8
  container_name: "kibana"
  hostname: "kibana"
  environment:
   LOGSPOUT: ignore
   ELASTICSEARCH_URL: http://elasticsearch:9200
   server.basePath: "/kibana"
  depends_on:
   - elasticsearch
  ports:
   - "127.0.0.1:5601:5601"
